name: Continuous Integration

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            .docusaurus
            build
            node_modules/.cache/webpack
          key: build-${{ hashFiles('blog/**') }}

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Run Build
        run: yarn run build
